apiVersion: v1
data:
  INFLUX_ORG: <ORG-base64>
  INFLUX_TOKEN: <Token-base64>
  MINIO_ACCESS_KEY: <AccessKey-base64>
  MINIO_SECRET_KEY: <SecretKey-base64>
  MONGO_PASS: <MongoPass-base64>
  MONGO_USER: <MongoUser-base64>
kind: Secret
metadata:
  name: backupaut-secret
  namespace: yourns
type: Opaque
